Importing Dependencies

In [9]:
import numpy as np
import pandas as pd
!pip install openpyxl
import openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Creating dataframe from the flight price data excel file

In [10]:
data = pd.read_excel("E:/Machine Learning/Flight Price Predictor/datasets/flight_price.xlsx")
df = pd.DataFrame(data)
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

# Observing the dataset and its features

### Number of rows and columns

In [11]:
df.shape

(10683, 11)

### Datatype as well as total non null data present in each of the columns

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

### Number of nulls present in each column

In [13]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [14]:
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

### Separating date, month and year into different columns from date of journey

In [15]:
Date = df['Date_of_Journey'].str.split('/').str[0].astype(int)
Month = df['Date_of_Journey'].str.split('/').str[1].astype(int)
Year = df['Date_of_Journey'].str.split('/').str[2].astype(int)

### Inserting the date, month and year columns in desired positions

In [16]:
df.insert(1, 'Date', Date)
df.insert(2, 'Month', Month)
df.insert(3, 'Year', Year)

In [17]:
df

,Airline,Date,Month,Year,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24,3,2019,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1,5,2019,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9,6,2019,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12,5,2019,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,1,3,2019,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9,4,2019,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27,4,2019,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27,4,2019,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,1,3,2019,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9,5,2019,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date             10683 non-null  int64
 2   Month            10683 non-null  int64
 3   Year             10683 non-null  int64
 4   Date_of_Journey  10683 non-null  object
 5   Source           10683 non-null  object
 6   Destination      10683 non-null  object
 7   Route            10682 non-null  object
 8   Dep_Time         10683 non-null  object
 9   Arrival_Time     10683 non-null  object
 10  Duration         10683 non-null  object
 11  Total_Stops      10682 non-null  object
 12  Additional_Info  10683 non-null  object
 13  Price            10683 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

### Dropping the date of journey column since we do not need it anymore

In [19]:
df.drop('Date_of_Journey', axis=1, inplace=True)

In [20]:
df

,Airline,Date,Month,Year,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24,3,2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1,5,2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9,6,2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12,5,2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,1,3,2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9,4,2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27,4,2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27,4,2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,1,3,2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9,5,2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

### Since we have source and destination as separate columns so Route column is redundant in our data

In [21]:
df.drop('Route', axis=1, inplace=True)
df

,Airline,Date,Month,Year,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24,3,2019,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1,5,2019,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9,6,2019,Delhi,Cochin,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12,5,2019,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,1,3,2019,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9,4,2019,Kolkata,Banglore,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27,4,2019,Kolkata,Banglore,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27,4,2019,Banglore,Delhi,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,1,3,2019,Banglore,New Delhi,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9,5,2019,Delhi,Cochin,10:55,19:15,8h 20m,2 stops,No info,11753

# Cleaning the arrival time column

### Splitting arrival time and date and keeping only arrival time as our useful data

In [22]:
df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x:x.split(" ")[0])

In [23]:
df

,Airline,Date,Month,Year,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24,3,2019,Banglore,New Delhi,22:20,01:10,2h 50m,non-stop,No info,3897
1,Air India,1,5,2019,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9,6,2019,Delhi,Cochin,09:25,04:25,19h,2 stops,No info,13882
3,IndiGo,12,5,2019,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,1,3,2019,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9,4,2019,Kolkata,Banglore,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27,4,2019,Kolkata,Banglore,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27,4,2019,Banglore,Delhi,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,1,3,2019,Banglore,New Delhi,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9,5,2019,Delhi,Cochin,10:55,19:15,8h 20m,2 stops,No info,11753

### Splitting arrival time into arrival hour and minute as separate columns

In [24]:
df['Arrival_hour']= df['Arrival_Time'].str.split(':').str[0].astype(int)
df['Arrival_minute']= df['Arrival_Time'].str.split(':').str[1].astype(int)

In [25]:
df

,Airline,Date,Month,Year,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Arrival_hour,Arrival_minute
0,IndiGo,24,3,2019,Banglore,New Delhi,22:20,01:10,2h 50m,non-stop,No info,3897,1,10
1,Air India,1,5,2019,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662,13,15
2,Jet Airways,9,6,2019,Delhi,Cochin,09:25,04:25,19h,2 stops,No info,13882,4,25
3,IndiGo,12,5,2019,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,No info,6218,23,30
4,IndiGo,1,3,2019,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,No info,13302,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9,4,2019,Kolkata,Banglore,19:55,22:25,2h 30m,non-stop,No info,4107,22,25
10679,Air India,27,4,2019,Kolkata,Banglore,20:45,23:20,2h 35m,non-stop,No info,4145,23,20
10680,Jet Airways,27,4,2019,Banglore,Delhi,08:20,11:20,3h,non-stop,No info,7229,11,20
10681,Vistara,1,3,2019,Banglore,New Delhi,11:30,14:10,2h 40m,non-stop,No info,12648,14,10
10682,Air India,9,5,2019,Delhi,Cochin,10:55,19:15,8h 20m,2 stops,No info,11753,19,15

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date             10683 non-null  int64
 2   Month            10683 non-null  int64
 3   Year             10683 non-null  int64
 4   Source           10683 non-null  object
 5   Destination      10683 non-null  object
 6   Dep_Time         10683 non-null  object
 7   Arrival_Time     10683 non-null  object
 8   Duration         10683 non-null  object
 9   Total_Stops      10682 non-null  object
 10  Additional_Info  10683 non-null  object
 11  Price            10683 non-null  int64
 12  Arrival_hour     10683 non-null  int64
 13  Arrival_minute   10683 non-null  int64
dtypes: int64(6), object(8)
memory usage: 1.1+ MB

### Dropping arrival time column since we do not need it any more

In [27]:
df.drop('Arrival_Time', axis=1, inplace=True)

In [28]:
df

,Airline,Date,Month,Year,Source,Destination,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Arrival_hour,Arrival_minute
0,IndiGo,24,3,2019,Banglore,New Delhi,22:20,2h 50m,non-stop,No info,3897,1,10
1,Air India,1,5,2019,Kolkata,Banglore,05:50,7h 25m,2 stops,No info,7662,13,15
2,Jet Airways,9,6,2019,Delhi,Cochin,09:25,19h,2 stops,No info,13882,4,25
3,IndiGo,12,5,2019,Kolkata,Banglore,18:05,5h 25m,1 stop,No info,6218,23,30
4,IndiGo,1,3,2019,Banglore,New Delhi,16:50,4h 45m,1 stop,No info,13302,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9,4,2019,Kolkata,Banglore,19:55,2h 30m,non-stop,No info,4107,22,25
10679,Air India,27,4,2019,Kolkata,Banglore,20:45,2h 35m,non-stop,No info,4145,23,20
10680,Jet Airways,27,4,2019,Banglore,Delhi,08:20,3h,non-stop,No info,7229,11,20
10681,Vistara,1,3,2019,Banglore,New Delhi,11:30,2h 40m,non-stop,No info,12648,14,10
10682,Air India,9,5,2019,Delhi,Cochin,10:55,8h 20m,2 stops,No info,11753,19,15

# Cleaning the departure time column

### Splitting departure time and date and keeping only arrival time as our useful data

In [29]:
df['Dep_Time'] = df['Dep_Time'].apply(lambda x:x.split(" ")[0])

### Splitting departure time into departure hour and minute as separate columns

In [30]:
df['Dep_hour']= df['Dep_Time'].str.split(':').str[0].astype(int)
df['Dep_minute']= df['Dep_Time'].str.split(':').str[1].astype(int)

In [31]:
df

,Airline,Date,Month,Year,Source,Destination,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute
0,IndiGo,24,3,2019,Banglore,New Delhi,22:20,2h 50m,non-stop,No info,3897,1,10,22,20
1,Air India,1,5,2019,Kolkata,Banglore,05:50,7h 25m,2 stops,No info,7662,13,15,5,50
2,Jet Airways,9,6,2019,Delhi,Cochin,09:25,19h,2 stops,No info,13882,4,25,9,25
3,IndiGo,12,5,2019,Kolkata,Banglore,18:05,5h 25m,1 stop,No info,6218,23,30,18,5
4,IndiGo,1,3,2019,Banglore,New Delhi,16:50,4h 45m,1 stop,No info,13302,21,35,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9,4,2019,Kolkata,Banglore,19:55,2h 30m,non-stop,No info,4107,22,25,19,55
10679,Air India,27,4,2019,Kolkata,Banglore,20:45,2h 35m,non-stop,No info,4145,23,20,20,45
10680,Jet Airways,27,4,2019,Banglore,Delhi,08:20,3h,non-stop,No info,7229,11,20,8,20
10681,Vistara,1,3,2019,Banglore,New Delhi,11:30,2h 40m,non-stop,No info,12648,14,10,11,30
10682,Air India,9,5,2019,Delhi,Cochin,10:55,8h 20m,2 stops,No info,11753,19,15,10,55

### Dropping departure time column as we do not need it anymore

In [32]:
df.drop('Dep_Time', axis=1, inplace=True)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date             10683 non-null  int64
 2   Month            10683 non-null  int64
 3   Year             10683 non-null  int64
 4   Source           10683 non-null  object
 5   Destination      10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Arrival_hour     10683 non-null  int64
 11  Arrival_minute   10683 non-null  int64
 12  Dep_hour         10683 non-null  int64
 13  Dep_minute       10683 non-null  int64
dtypes: int64(8), object(6)
memory usage: 1.1+ MB

In [34]:
df

,Airline,Date,Month,Year,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute
0,IndiGo,24,3,2019,Banglore,New Delhi,2h 50m,non-stop,No info,3897,1,10,22,20
1,Air India,1,5,2019,Kolkata,Banglore,7h 25m,2 stops,No info,7662,13,15,5,50
2,Jet Airways,9,6,2019,Delhi,Cochin,19h,2 stops,No info,13882,4,25,9,25
3,IndiGo,12,5,2019,Kolkata,Banglore,5h 25m,1 stop,No info,6218,23,30,18,5
4,IndiGo,1,3,2019,Banglore,New Delhi,4h 45m,1 stop,No info,13302,21,35,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9,4,2019,Kolkata,Banglore,2h 30m,non-stop,No info,4107,22,25,19,55
10679,Air India,27,4,2019,Kolkata,Banglore,2h 35m,non-stop,No info,4145,23,20,20,45
10680,Jet Airways,27,4,2019,Banglore,Delhi,3h,non-stop,No info,7229,11,20,8,20
10681,Vistara,1,3,2019,Banglore,New Delhi,2h 40m,non-stop,No info,12648,14,10,11,30
10682,Air India,9,5,2019,Delhi,Cochin,8h 20m,2 stops,No info,11753,19,15,10,55

# Checking whether all the data entries in Duration column are in the format %h %m.

### Encountered that some data is in the format of %m only.

In [35]:
df['Duration'].str.split(" ").str[0].str.split("h").str[0].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', '5m', '41', '40'], dtype=object)

### Finding how many data are in %m format

In [36]:
df[df['Duration'].eq('5m')]

,Airline,Date,Month,Year,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute
6474,Air India,6,3,2019,Mumbai,Hyderabad,5m,2 stops,No info,17327,16,55,16,50

### Since there are very few data (here 1 only) in %m format, we can handle it manually

In [37]:
df.loc[df['Duration']=='5m', 'Duration'] = '0h 5m'

### Splitting duration into duration hour and duration minute as separate columns

In [38]:
df['Duration_hour'] = df['Duration'].str.split(" ").str[0].str.split("h").str[0]
df['Duration_minute'] = df['Duration'].str.split(" ").str[1].str.split("m").str[0]
df.head(2)

,Airline,Date,Month,Year,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute,Duration_hour,Duration_minute
0,IndiGo,24,3,2019,Banglore,New Delhi,2h 50m,non-stop,No info,3897,1,10,22,20,2,50
1,Air India,1,5,2019,Kolkata,Banglore,7h 25m,2 stops,No info,7662,13,15,5,50,7,25

### Some data is in the format of %h as well. As a result duration minute has only 9651 non null values.

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date             10683 non-null  int64
 2   Month            10683 non-null  int64
 3   Year             10683 non-null  int64
 4   Source           10683 non-null  object
 5   Destination      10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Arrival_hour     10683 non-null  int64
 11  Arrival_minute   10683 non-null  int64
 12  Dep_hour         10683 non-null  int64
 13  Dep_minute       10683 non-null  int64
 14  Duration_hour    10683 non-null  object
 15  Duration_minute  9652 non-null   object
dtypes: int64(8), object(8)
memory usage: 1.3+ MB

### Filling the empty places in duration minute with 0

In [40]:
df['Duration_minute'].fillna(0, inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_21648\4229254387.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Duration_minute'].fillna(0, inplace=True)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date             10683 non-null  int64
 2   Month            10683 non-null  int64
 3   Year             10683 non-null  int64
 4   Source           10683 non-null  object
 5   Destination      10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Arrival_hour     10683 non-null  int64
 11  Arrival_minute   10683 non-null  int64
 12  Dep_hour         10683 non-null  int64
 13  Dep_minute       10683 non-null  int64
 14  Duration_hour    10683 non-null  object
 15  Duration_minute  10683 non-null  object
dtypes: int64(8), object(8)
memory usage: 1.3+ MB

### Converting duration columns to int type

In [42]:
df['Duration_hour'] = df['Duration_hour'].astype(int)
df['Duration_minute'] = df['Duration_minute'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date             10683 non-null  int64
 2   Month            10683 non-null  int64
 3   Year             10683 non-null  int64
 4   Source           10683 non-null  object
 5   Destination      10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Arrival_hour     10683 non-null  int64
 11  Arrival_minute   10683 non-null  int64
 12  Dep_hour         10683 non-null  int64
 13  Dep_minute       10683 non-null  int64
 14  Duration_hour    10683 non-null  int64
 15  Duration_minute  10683 non-null  int64
dtypes: int64(10), object(6)
memory usage: 1.3+ MB

### Dropping duration column since we do not need it anymore

In [43]:
df.drop("Duration", axis=1, inplace=True)
df

,Airline,Date,Month,Year,Source,Destination,Total_Stops,Additional_Info,Price,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute,Duration_hour,Duration_minute
0,IndiGo,24,3,2019,Banglore,New Delhi,non-stop,No info,3897,1,10,22,20,2,50
1,Air India,1,5,2019,Kolkata,Banglore,2 stops,No info,7662,13,15,5,50,7,25
2,Jet Airways,9,6,2019,Delhi,Cochin,2 stops,No info,13882,4,25,9,25,19,0
3,IndiGo,12,5,2019,Kolkata,Banglore,1 stop,No info,6218,23,30,18,5,5,25
4,IndiGo,1,3,2019,Banglore,New Delhi,1 stop,No info,13302,21,35,16,50,4,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9,4,2019,Kolkata,Banglore,non-stop,No info,4107,22,25,19,55,2,30
10679,Air India,27,4,2019,Kolkata,Banglore,non-stop,No info,4145,23,20,20,45,2,35
10680,Jet Airways,27,4,2019,Banglore,Delhi,non-stop,No info,7229,11,20,8,20,3,0
10681,Vistara,1,3,2019,Banglore,New Delhi,non-stop,No info,12648,14,10,11,30,2,40
10682,Air India,9,5,2019,Delhi,Cochin,2 stops,No info,11753,19,15,10,55,8,20

# Checking the number of unique values in the remaining categorical columns

In [44]:
df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [45]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [46]:
df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [47]:
df['Source'].unique()

array(['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai'], dtype=object)

In [48]:
df['Destination'].unique()

array(['New Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Delhi', 'Hyderabad'],
      dtype=object)

### Since Total stops has only 1 null value, we will be filling that with its mode.

In [49]:
df['Total_Stops'].mode()

0    1 stop
Name: Total_Stops, dtype: object

### Mapping the total stops to a designated unique value that represents their importance or order as well

In [50]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop' : 0, '1 stop' : 1, '2 stops' : 2, '3 stops' : 3, '4 stops' : 4, np.nan : 1})

In [51]:
df

,Airline,Date,Month,Year,Source,Destination,Total_Stops,Additional_Info,Price,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute,Duration_hour,Duration_minute
0,IndiGo,24,3,2019,Banglore,New Delhi,0,No info,3897,1,10,22,20,2,50
1,Air India,1,5,2019,Kolkata,Banglore,2,No info,7662,13,15,5,50,7,25
2,Jet Airways,9,6,2019,Delhi,Cochin,2,No info,13882,4,25,9,25,19,0
3,IndiGo,12,5,2019,Kolkata,Banglore,1,No info,6218,23,30,18,5,5,25
4,IndiGo,1,3,2019,Banglore,New Delhi,1,No info,13302,21,35,16,50,4,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9,4,2019,Kolkata,Banglore,0,No info,4107,22,25,19,55,2,30
10679,Air India,27,4,2019,Kolkata,Banglore,0,No info,4145,23,20,20,45,2,35
10680,Jet Airways,27,4,2019,Banglore,Delhi,0,No info,7229,11,20,8,20,3,0
10681,Vistara,1,3,2019,Banglore,New Delhi,0,No info,12648,14,10,11,30,2,40
10682,Air India,9,5,2019,Delhi,Cochin,2,No info,11753,19,15,10,55,8,20

### Importing OneHotEncoder to encode the categorical values and make it suitable for the machine to understand

In [52]:
from sklearn.preprocessing import OneHotEncoder

In [53]:
encoder = OneHotEncoder()

### Transforming the columns Airline, Source and Destination to their encoded terms

In [54]:
encoder.fit_transform(df[['Airline', 'Source', 'Destination']]).toarray()

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(10683, 23))

In [55]:
encoded = pd.DataFrame(encoder.fit_transform(df[['Airline', 'Source', 'Destination']]).toarray(), columns=encoder.get_feature_names_out())

In [56]:
encoded

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10679,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10680,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10682,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

### Dropping the original categorical columns since they are not needed anymore.

In [57]:
df.drop(['Airline', 'Source', 'Destination', 'Additional_Info'], axis=1, inplace=True)

In [58]:
df

,Date,Month,Year,Total_Stops,Price,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute,Duration_hour,Duration_minute
0,24,3,2019,0,3897,1,10,22,20,2,50
1,1,5,2019,2,7662,13,15,5,50,7,25
2,9,6,2019,2,13882,4,25,9,25,19,0
3,12,5,2019,1,6218,23,30,18,5,5,25
4,1,3,2019,1,13302,21,35,16,50,4,45
...,...,...,...,...,...,...,...,...,...,...,...
10678,9,4,2019,0,4107,22,25,19,55,2,30
10679,27,4,2019,0,4145,23,20,20,45,2,35
10680,27,4,2019,0,7229,11,20,8,20,3,0
10681,1,3,2019,0,12648,14,10,11,30,2,40
10682,9,5,2019,2,11753,19,15,10,55,8,20

### Shifting the price column to the last since it represents the target column

In [59]:
target = df.pop('Price')
df.insert(10, 'Price', target)
df

,Date,Month,Year,Total_Stops,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute,Duration_hour,Duration_minute,Price
0,24,3,2019,0,1,10,22,20,2,50,3897
1,1,5,2019,2,13,15,5,50,7,25,7662
2,9,6,2019,2,4,25,9,25,19,0,13882
3,12,5,2019,1,23,30,18,5,5,25,6218
4,1,3,2019,1,21,35,16,50,4,45,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,9,4,2019,0,22,25,19,55,2,30,4107
10679,27,4,2019,0,23,20,20,45,2,35,4145
10680,27,4,2019,0,11,20,8,20,3,0,7229
10681,1,3,2019,0,14,10,11,30,2,40,12648
10682,9,5,2019,2,19,15,10,55,8,20,11753

### Concatinating the numerical columns and encoded categorical columns to form our final dataframe suitable for model training.

In [60]:
df_clean=pd.concat([encoded,df], axis=1)

In [61]:
df_clean

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,...,Month,Year,Total_Stops,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute,Duration_hour,Duration_minute,Price
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3,2019,0,1,10,22,20,2,50,3897
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5,2019,2,13,15,5,50,7,25,7662
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,6,2019,2,4,25,9,25,19,0,13882
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5,2019,1,23,30,18,5,5,25,6218
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3,2019,1,21,35,16,50,4,45,13302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4,2019,0,22,25,19,55,2,30,4107
10679,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4,2019,0,23,20,20,45,2,35,4145
10680,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,4,2019,0,11,20,8,20,3,0,7229
10681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3,2019,0,14,10,11,30,2,40,12648
10682,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5,2019,2,19,15,10,55,8,20,11753

### Verifying if there are any left out null values

In [62]:
df_clean.isnull().sum().sum()

np.int64(0)

### Verifying every column is of numeric datatype

In [63]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 34 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Airline_Air Asia                           10683 non-null  float64
 1   Airline_Air India                          10683 non-null  float64
 2   Airline_GoAir                              10683 non-null  float64
 3   Airline_IndiGo                             10683 non-null  float64
 4   Airline_Jet Airways                        10683 non-null  float64
 5   Airline_Jet Airways Business               10683 non-null  float64
 6   Airline_Multiple carriers                  10683 non-null  float64
 7   Airline_Multiple carriers Premium economy  10683 non-null  float64
 8   Airline_SpiceJet                           10683 non-null  float64
 9   Airline_Trujet                             10683 non-null  float64
 10  Airline_Vistara                            10683 non-null  float64
 11  Airline_Vistara Premium economy            10683 non-null  float64
 12  Source_Banglore                            10683 non-null  float64
 13  Source_Chennai                             10683 non-null  float64
 14  Source_Delhi                               10683 non-null  float64
 15  Source_Kolkata                             10683 non-null  float64
 16  Source_Mumbai                              10683 non-null  float64
 17  Destination_Banglore                       10683 non-null  float64
 18  Destination_Cochin                         10683 non-null  float64
 19  Destination_Delhi                          10683 non-null  float64
 20  Destination_Hyderabad                      10683 non-null  float64
 21  Destination_Kolkata                        10683 non-null  float64
 22  Destination_New Delhi                      10683 non-null  float64
 23  Date                                       10683 non-null  int64
 24  Month                                      10683 non-null  int64
 25  Year                                       10683 non-null  int64
 26  Total_Stops                                10683 non-null  int64
 27  Arrival_hour                               10683 non-null  int64
 28  Arrival_minute                             10683 non-null  int64
 29  Dep_hour                                   10683 non-null  int64
 30  Dep_minute                                 10683 non-null  int64
 31  Duration_hour                              10683 non-null  int64
 32  Duration_minute                            10683 non-null  int64
 33  Price                                      10683 non-null  int64
dtypes: float64(23), int64(11)
memory usage: 2.8 MB

In [64]:
df_clean.to_csv("flight_price_cleaned.csv", index=False)